// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_sJv1-kdqzDQIUU-Z2OMUcotCEq8O-Hc',
    appId: '1:218349720331:web:6206aa76bc5fd0f604480e',
    messagingSenderId: '218349720331',
    projectId: 'flutter-quiz-app-35053',
    authDomain: 'flutter-quiz-app-35053.firebaseapp.com',
    databaseURL: 'https://flutter-quiz-app-35053-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-quiz-app-35053.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb9n_7uD-jIvN5aiYOU6xbnldkYnJU--o',
    appId: '1:218349720331:android:b3f5a2dbe3b0007604480e',
    messagingSenderId: '218349720331',
    projectId: 'flutter-quiz-app-35053',
    databaseURL: 'https://flutter-quiz-app-35053-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-quiz-app-35053.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxX9ZQ_R1UPpDPgsWnjVh1kBSTYucaB9E',
    appId: '1:218349720331:ios:654dd0a28f6a9fc804480e',
    messagingSenderId: '218349720331',
    projectId: 'flutter-quiz-app-35053',
    databaseURL: 'https://flutter-quiz-app-35053-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-quiz-app-35053.appspot.com',
    iosBundleId: 'com.example.flutterQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxX9ZQ_R1UPpDPgsWnjVh1kBSTYucaB9E',
    appId: '1:218349720331:ios:531941e7b3b3df3c04480e',
    messagingSenderId: '218349720331',
    projectId: 'flutter-quiz-app-35053',
    databaseURL: 'https://flutter-quiz-app-35053-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-quiz-app-35053.appspot.com',
    iosBundleId: 'com.example.flutterQuizApp.RunnerTests',
  );
}
